---
sudo: false
notifications:
  on_success: change
  on_failure: always

dist: trusty
language: python
install: pip install tox-travis
script: tox

matrix:
  include:
    - python: 3.6
      env: TOXENV=lint TRAVIS=yes
    - python: pypy3
      env: TOXENV=pypy3-functional,pypy3-unit TRAVIS=yes
    - python: pypy
      env: TOXENV=pypy-functional,pypy-unit TRAVIS=yes
    - python: 3.6
      env: TOXENV=py36-functional,py36-unit TRAVIS=yes
    - python: 3.5
      env: TOXENV=py35-functional,py35-unit TRAVIS=yes
    - python: 3.4
      env: TOXENV=py34-functional,py34-unit TRAVIS=yes
    - python: 3.3
      env: TOXENV=py33-functional,py33-unit TRAVIS=yes
    - python: 2.7
      env: TOXENV=py27-functional,py27-unit TRAVIS=yes
    - python: 2.6
      env: TOXENV=py26-functional,py26-unit TRAVIS=yes
